/**
 * Cross-platform installer templates served from
 * `/api/onboard.sh` (POSIX) and `/api/onboard.ps1` (Windows).
 *
 * Each installer wires three things:
 *   1. `claude mcp add brain ...` — register the MCP server with the user-
 *      level Claude Code config (writes ~/.claude.json or %USERPROFILE%\
 *      .claude.json — NOT ~/.claude/mcp.json, which is the trap users hit).
 *   2. Download SKILL.md → ~/.claude/skills/brain/SKILL.md (POSIX) or
 *      %USERPROFILE%\.claude\skills\brain\SKILL.md (Windows).
 *   3. Verify with `claude mcp list`.
 *
 * Token is passed as the first positional arg, NOT inlined at template
 * time — that lets the same installer URL be cached publicly while
 * each operator pastes their own bearer at run time.
 *
 *   POSIX:    curl -fsSL https://<webhost>/api/onboard.sh | bash -s <token>
 *   Windows:  iwr https://<webhost>/api/onboard.ps1 -UseBasicParsing |
 *               iex; Install-Brain -Token '<token>'
 *
 * Reviewer-friendly variants (download → inspect → run) are documented in
 * docs/CLIENTS.md.
 */

export interface InstallerOpts {
  mcpUrl: string; // public MCP endpoint (HTTPS or HTTP-with-port for dev)
  webUrl: string; // public webapp origin — used for the SKILL.md fetch URL
}

export function bashInstaller(opts: InstallerOpts): string {
  return `#!/usr/bin/env bash
# External Brain — POSIX installer (macOS / Linux / WSL / Git Bash).
# Generated by ${opts.webUrl}/api/onboard.sh — do not commit to a repo
# unless you also commit a token-redaction step.
#
# Usage:
#   curl -fsSL ${opts.webUrl}/api/onboard.sh | bash -s 'bp_…'
#   # or, audit-first:
#   curl -fsSL ${opts.webUrl}/api/onboard.sh -o /tmp/brain-install.sh
#   less /tmp/brain-install.sh
#   bash /tmp/brain-install.sh 'bp_…'

set -eu

TOKEN="\${1:-}"
if [ -z "$TOKEN" ]; then
  echo "ERROR: pass the token as the first argument." >&2
  echo "Get a token at ${opts.webUrl}/settings/tokens" >&2
  exit 1
fi
if ! printf '%s' "$TOKEN" | grep -qE '^bp_[A-Za-z0-9_-]{20,}$'; then
  echo "ERROR: token doesn't look like a Brain bearer (expected bp_…)." >&2
  exit 1
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "ERROR: 'claude' CLI not found on PATH." >&2
  echo "Install Claude Code first: https://docs.claude.com/en/docs/claude-code" >&2
  exit 1
fi

echo "==> Registering Brain MCP with Claude Code (user scope)…"
# Capture both stdout and stderr — \`claude mcp add\` prints the
# "already exists" hint to either depending on version.
ADD_OUTPUT=$(claude mcp add brain \\
  --scope user \\
  --transport http \\
  '${opts.mcpUrl}' \\
  --header "Authorization: Bearer $TOKEN" 2>&1) || ADD_RC=$?

if [ "\${ADD_RC:-0}" -ne 0 ]; then
  echo "$ADD_OUTPUT"
  if printf '%s' "$ADD_OUTPUT" | grep -qi 'already exists'; then
    cat <<EOF >&2

A 'brain' MCP server is already registered. Remove it and re-run:

  claude mcp remove brain --scope user
  curl -fsSL ${opts.webUrl}/api/onboard.sh | bash -s '\$TOKEN'

(Re-paste the same bp_… token. If the existing entry points at a
different Brain you want to keep, hand-edit \$HOME/.claude.json to
give one of them a different key — the user-scope namespace is keyed
by name and 'brain' is the name this installer uses.)

EOF
    exit 1
  fi
  echo "ERROR: 'claude mcp add brain' failed:" >&2
  echo "$ADD_OUTPUT" >&2
  exit 1
fi
echo "$ADD_OUTPUT"

SKILL_DIR="$HOME/.claude/skills/brain"
echo "==> Installing skill at $SKILL_DIR/SKILL.md…"
mkdir -p "$SKILL_DIR"
if command -v curl >/dev/null 2>&1; then
  curl -fsSL '${opts.webUrl}/api/skills/brain' -o "$SKILL_DIR/SKILL.md"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$SKILL_DIR/SKILL.md" '${opts.webUrl}/api/skills/brain'
else
  echo "ERROR: neither curl nor wget found. Install one and retry." >&2
  exit 1
fi

echo "==> Verifying with \\\`claude mcp list\\\`…"
if claude mcp list 2>&1 | grep -q '^brain:'; then
  echo "    config OK"
else
  echo "WARN: Brain entry not visible in \\\`claude mcp list\\\` — restart Claude Code and retry." >&2
fi

# ----------------------------------------------------------------------
# Reconcile legacy \$HOME/.claude/mcp.json (#222, 2026-05-15)
#
# Some prior Claude Code versions wrote MCP server config to a separate
# file at \$HOME/.claude/mcp.json. Modern \`claude mcp add\` writes to
# \$HOME/.claude.json (top-level \`mcpServers\` key) but does NOT touch
# the legacy file. The CLI still READS both, with the legacy file
# shadowing the modern one on some versions — which means a freshly-
# installed token in .claude.json gets silently overridden by stale
# config in .claude/mcp.json, and the next Claude Code session calls
# the wrong (often decommissioned) host with an old token.
#
# Reconciliation:
#   1. If \$HOME/.claude/mcp.json doesn't exist → no-op.
#   2. If it exists and has a \`brain\` entry → strip the brain entry.
#      - If the file becomes empty {} or {"mcpServers":{}} → delete it.
#      - Otherwise rewrite it preserving any non-brain entries.
#   3. Idempotent — second run sees no brain entry and is a clean no-op.
#
# Plain bash + grep/sed instead of jq because jq isn't guaranteed on
# all POSIX hosts (macOS without homebrew, fresh Debian slim images).
# ----------------------------------------------------------------------
LEGACY_MCP_JSON="\$HOME/.claude/mcp.json"
if [ -f "\$LEGACY_MCP_JSON" ]; then
  # Detect whether the legacy file mentions \"brain\" at all.
  if grep -q '"brain"' "\$LEGACY_MCP_JSON" 2>/dev/null; then
    LEGACY_OLD_URL=\$(grep -oE '"url"[[:space:]]*:[[:space:]]*"[^"]*"' "\$LEGACY_MCP_JSON" | head -1 | sed 's/.*"\\(http[^"]*\\)".*/\\1/')
    echo "==> Cleaning legacy \$LEGACY_MCP_JSON (was: \${LEGACY_OLD_URL:-unknown URL})…"
    # Use Python (always available on macOS + most Linux distros, unlike
    # jq) to surgically remove the brain entry. Falls back to deletion
    # if Python is missing AND we're confident brain is the only entry.
    if command -v python3 >/dev/null 2>&1; then
      python3 - "\$LEGACY_MCP_JSON" <<'PY'
import json, os, sys
p = sys.argv[1]
try:
    with open(p) as f:
        d = json.load(f)
except Exception:
    sys.exit(0)
# Two shapes seen: { "mcpServers": { "brain": {...} } } AND { "brain": {...} } at top level.
changed = False
if isinstance(d.get("mcpServers"), dict) and "brain" in d["mcpServers"]:
    del d["mcpServers"]["brain"]
    changed = True
if isinstance(d, dict) and "brain" in d and not isinstance(d.get("brain"), str):
    del d["brain"]
    changed = True
# If file is now empty of meaningful content, remove it entirely.
def is_empty(x):
    if not isinstance(x, dict): return False
    if not x: return True
    return all(k == "mcpServers" and not v for k, v in x.items())
if is_empty(d):
    os.unlink(p)
    print("    legacy file had only the brain entry — removed", flush=True)
elif changed:
    with open(p, "w") as f:
        json.dump(d, f, indent=2)
    print("    stripped brain entry; preserved other servers", flush=True)
else:
    print("    no brain entry found in legacy file — left untouched", flush=True)
PY
    else
      # Conservative bash-only fallback: only delete if the file looks like
      # it ONLY contains a brain entry (the dominant case observed in #222).
      # Otherwise warn the user and stop short of destroying their config.
      if [ "\$(wc -l < "\$LEGACY_MCP_JSON")" -le 5 ] && grep -q '"brain"' "\$LEGACY_MCP_JSON"; then
        rm -f "\$LEGACY_MCP_JSON"
        echo "    removed (single-entry legacy file)"
      else
        echo "WARN: \$LEGACY_MCP_JSON has multiple entries and python3 isn't installed." >&2
        echo "      Manually remove the 'brain' entry to avoid stale-config drift." >&2
      fi
    fi
  fi
fi

# ----------------------------------------------------------------------
# Smoke-test (I1) — prove the round-trip works through the user's
# network, TLS, Caddy, the MCP server, and authenticate() against the
# DB. The earlier \\\`claude mcp list\\\` step only verifies the local
# config file; it does NOT prove the bearer reaches a tool. A common
# silent failure: install reports success while the client can never
# call a tool (proxy / firewall / DNS / revoked token).
# ----------------------------------------------------------------------
echo "==> Smoke-testing the MCP round-trip…"
MCP_URL='${opts.mcpUrl}'
SMOKE_TMP="\$(mktemp -t brainsmoke.XXXXXX)"
trap 'rm -f "\$SMOKE_TMP" "\$SMOKE_TMP.h"' EXIT
INIT_BODY='{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"brain-installer","version":"2"}}}'
HTTP=\$(curl -sS -o "\$SMOKE_TMP" -D "\$SMOKE_TMP.h" -w '%{http_code}' \\
  -H "Authorization: Bearer \$TOKEN" \\
  -H 'Content-Type: application/json' \\
  -H 'Accept: application/json, text/event-stream' \\
  --max-time 15 -X POST "\$MCP_URL" --data "\$INIT_BODY") || HTTP=000
if [ "\$HTTP" != "200" ]; then
  echo "ERROR: MCP initialize returned HTTP \$HTTP" >&2
  echo "  URL: \$MCP_URL" >&2
  case "\$HTTP" in
    401) echo "  Cause: token rejected — mint a fresh one at ${opts.webUrl}/settings/tokens" >&2 ;;
    000) echo "  Cause: connection failed (DNS, TLS, or firewall block)." >&2 ;;
    502|503|504) echo "  Cause: Brain reachable but MCP backend unhealthy. Retry in 60s." >&2 ;;
    404) echo "  Cause: MCP endpoint not found at this URL — installer template may be stale." >&2 ;;
  esac
  exit 1
fi
SID=\$(grep -i '^mcp-session-id:' "\$SMOKE_TMP.h" | sed 's/^[^:]*: *//; s/[[:space:]]*\$//' | head -1)
if [ -z "\$SID" ]; then
  echo "ERROR: MCP did not issue Mcp-Session-Id — transport may be misconfigured." >&2
  exit 1
fi
CALL_BODY='{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"brain_get_user_style","arguments":{}}}'
HTTP=\$(curl -sS -o "\$SMOKE_TMP" -w '%{http_code}' \\
  -H "Authorization: Bearer \$TOKEN" \\
  -H "Mcp-Session-Id: \$SID" \\
  -H 'Content-Type: application/json' \\
  -H 'Accept: application/json, text/event-stream' \\
  --max-time 15 -X POST "\$MCP_URL" --data "\$CALL_BODY") || HTTP=000
if [ "\$HTTP" != "200" ] || ! grep -q '"result"' "\$SMOKE_TMP"; then
  echo "ERROR: brain_get_user_style failed (HTTP \$HTTP). Response:" >&2
  sed 's/^/  /' "\$SMOKE_TMP" >&2
  exit 1
fi
echo "    round-trip OK (session \$SID)"

# ----------------------------------------------------------------------
# Install-ping (I2) — best-effort. Creates a real Session in Brain with
# clientType=claude_code, logs the installer + CLI + OS version, and
# reports the outcome so the KEA pipeline has its first signal. Failures
# here are non-fatal: I1 above already proved the round-trip; this just
# seeds the dashboard so the operator can distinguish new installs from
# stale heartbeats.
# ----------------------------------------------------------------------
echo "==> Logging install ping…"
CLAUDE_V=\$(claude --version 2>/dev/null | head -1 | tr -d '"' | sed 's/[^A-Za-z0-9. -]//g')
OS_INFO=\$(uname -srm 2>/dev/null | sed 's/[^A-Za-z0-9. _/-]//g')
START_BODY='{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"brain_start_session","arguments":{"clientType":"claude_code","prompt":"brain installer ping v2"}}}'
curl -sS -o "\$SMOKE_TMP" \\
  -H "Authorization: Bearer \$TOKEN" -H "Mcp-Session-Id: \$SID" \\
  -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \\
  --max-time 15 -X POST "\$MCP_URL" --data "\$START_BODY" >/dev/null || true
# The response wraps the sessionId inside a JSON string with escaped quotes
# (\\"sessionId\\": \\"cmp…\\") so a naive sed for "sessionId":"..." misses
# the actual bytes. Cuids in this codebase are c + 24 lowercase alnum chars
# and are the only cuid-shaped token in the start_session response, so
# grep-for-cuid is robust to whatever quoting the JSON-RPC layer adds.
NEW_SID=\$(grep -oE 'c[a-z0-9]{24}' "\$SMOKE_TMP" | head -1)
if [ -n "\$NEW_SID" ]; then
  EV_PAYLOAD=\$(printf '{"installer_version":2,"claude_version":"%s","os":"%s"}' "\$CLAUDE_V" "\$OS_INFO")
  EV_BODY=\$(printf '{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"brain_log_event","arguments":{"sessionId":"%s","eventType":"tool_use","payload":%s}}}' "\$NEW_SID" "\$EV_PAYLOAD")
  curl -sS -o /dev/null \\
    -H "Authorization: Bearer \$TOKEN" -H "Mcp-Session-Id: \$SID" \\
    -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \\
    --max-time 15 -X POST "\$MCP_URL" --data "\$EV_BODY" || true
  CLOSE_BODY=\$(printf '{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"brain_report_session_outcome","arguments":{"sessionId":"%s","success":true}}}' "\$NEW_SID")
  curl -sS -o /dev/null \\
    -H "Authorization: Bearer \$TOKEN" -H "Mcp-Session-Id: \$SID" \\
    -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' \\
    --max-time 15 -X POST "\$MCP_URL" --data "\$CLOSE_BODY" || true
  echo "    install ping recorded (session \$NEW_SID)"
fi

echo
echo "✓ Brain installed and verified."
echo
echo "  To prove your Brain is learning, paste this into a new Claude Code session:"
echo
echo "    Brain, remember: I prefer pgvector for embeddings on this project,"
echo "    because it co-locates with Postgres backups."
echo
echo "  Claude will call brain_teach_knowledge. See the fact appear at:"
# The app's surfaces are HASH routes inside the SPA shell at
# /<org>/<project> (lib/brain/routes.ts) — a bare /skills path 404s.
# "/" resolves the active project and 307s to its canonical URL; the
# fragment is client-side so it survives the redirect.
echo "    ${opts.webUrl}/#skills"
echo "  Restart Claude Code first so the new MCP entry is picked up."
`;
}

export function powershellInstaller(opts: InstallerOpts): string {
  return `# External Brain — Windows PowerShell installer.
# Generated by ${opts.webUrl}/api/onboard.ps1
#
# Usage (PowerShell 5.1 or 7+):
#   iwr ${opts.webUrl}/api/onboard.ps1 -UseBasicParsing | iex
#   Install-Brain -Token 'bp_…'
#
# Audit-first variant:
#   iwr ${opts.webUrl}/api/onboard.ps1 -OutFile $env:TEMP\\brain-install.ps1
#   notepad $env:TEMP\\brain-install.ps1
#   . $env:TEMP\\brain-install.ps1 ; Install-Brain -Token 'bp_…'

function Install-Brain {
  param(
    [Parameter(Mandatory=$true, Position=0)] [string] $Token
  )

  $ErrorActionPreference = 'Stop'

  if ($Token -notmatch '^bp_[A-Za-z0-9_-]{20,}$') {
    Write-Error "Token doesn't look like a Brain bearer (expected bp_…). Get one at ${opts.webUrl}/settings/tokens"
    return
  }

  if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Error "'claude' CLI not found on PATH. Install Claude Code first: https://docs.claude.com/en/docs/claude-code"
    return
  }

  Write-Host "==> Registering Brain MCP with Claude Code (user scope)…"
  $addOutput = & claude mcp add brain \`
    --scope user \`
    --transport http \`
    '${opts.mcpUrl}' \`
    --header "Authorization: Bearer $Token" 2>&1 | Out-String
  if ($LASTEXITCODE -ne 0) {
    Write-Host $addOutput
    if ($addOutput -match '(?i)already exists') {
      Write-Host ""
      Write-Host "A 'brain' MCP server is already registered. Remove it and re-run:" -ForegroundColor Yellow
      Write-Host ""
      Write-Host "  claude mcp remove brain --scope user"
      Write-Host "  iwr ${opts.webUrl}/api/onboard.ps1 -UseBasicParsing | iex"
      Write-Host "  Install-Brain -Token '<paste-the-same-bp_-token>'"
      Write-Host ""
      Write-Host "(If the existing entry points at a different Brain you want to keep,"
      Write-Host " hand-edit \`$env:USERPROFILE\\.claude.json to give one of them a different"
      Write-Host " key — the user-scope namespace is keyed by name and 'brain' is the name"
      Write-Host " this installer uses.)"
      Write-Host ""
      return
    }
    Write-Error "claude mcp add failed (exit $LASTEXITCODE):\`n$addOutput"
    return
  }
  Write-Host $addOutput

  $SkillDir = Join-Path $env:USERPROFILE '.claude\\skills\\brain'
  Write-Host "==> Installing skill at $SkillDir\\SKILL.md…"
  New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
  Invoke-WebRequest -Uri '${opts.webUrl}/api/skills/brain' \`
                    -OutFile (Join-Path $SkillDir 'SKILL.md') \`
                    -UseBasicParsing

  Write-Host "==> Verifying with \\\`claude mcp list\\\`…"
  $list = & claude mcp list 2>&1 | Out-String
  if ($list -match '(?m)^brain:') {
    Write-Host ""
    Write-Host "✓ Brain installed." -ForegroundColor Green
    Write-Host "  Restart Claude Code to load the skill, then start a new session."
    Write-Host "  Verify any time with: claude mcp list | findstr brain"
  } else {
    Write-Warning "Brain entry not visible in 'claude mcp list' — restart Claude Code and retry."
  }
}

# Auto-run if a $BrainToken global is set (for one-liner curl|iex flows).
if ($BrainToken) { Install-Brain -Token $BrainToken }
`;
}
